apiVersion: latest
enabled: true
name: txt2img-sd2-ipu
region: clehbtvty
image: joshuapaperspace/txt2img-sd2-ipu:latest
port: 80
healthChecks:
  readiness:
    path: /
resources:
  replicas: 1
  instanceType: IPU-POD16
  autoscaling:
    enabled: true
    maxReplicas: 2
    metrics:
      - metric: requestDuration
        summary: average
        value: 15
      - metric: cpu
        summary: average
        value: 85
      - metric: memory
        summary: average
        value: 85